<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[验证在登录界面，输入正确的手机号和密码，点击登录按钮后，可以正常登录成功，并跳转至首页主界面]]>
    </line>
  </reporter-output>
  <suite name="Appium测试报告" duration-ms="97988" started-at="2018-11-01T02:33:33Z" finished-at="2018-11-01T02:35:11Z">
    <groups>
    </groups>
    <test name="微信登录流程" duration-ms="97988" started-at="2018-11-01T02:33:33Z" finished-at="2018-11-01T02:35:11Z">
      <class name="TestCases.WeChatLogin">
        <test-method status="PASS" signature="stup()[pri:0, instance:TestCases.WeChatLogin@34c4973]" name="stup" is-config="true" duration-ms="66319" started-at="2018-11-01T10:33:33Z" finished-at="2018-11-01T10:34:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stup -->
        <test-method status="FAIL" signature="case1()[pri:0, instance:TestCases.WeChatLogin@34c4973]" name="case1" duration-ms="8628" started-at="2018-11-01T10:34:40Z" finished-at="2018-11-01T10:34:48Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at AutomationTestSystem.Service.RunUnitService.runCase(RunUnitService.java:85)
	at TestCases.WeChatLogin.case1(WeChatLogin.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: 进入登录界面失败(实际结果和预期结果不一致)  Actual 【手机号登录】  but found 【手机号登录1】
	at org.testng.Assert.fail(Assert.java:94)
	at AutomationTestSystem.Handler.CheckActionHandler.checkEqualsAndroid(CheckActionHandler.java:152)
	at AutomationTestSystem.Handler.CheckActionHandler.androidCheck(CheckActionHandler.java:48)
	... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case1 -->
        <test-method status="PASS" signature="case2()[pri:0, instance:TestCases.WeChatLogin@34c4973]" name="case2" duration-ms="20373" started-at="2018-11-01T10:34:48Z" finished-at="2018-11-01T10:35:09Z">
          <reporter-output>
            <line>
              <![CDATA[验证在登录界面，输入正确的手机号和密码，点击登录按钮后，可以正常登录成功，并跳转至首页主界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case2 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:TestCases.WeChatLogin@34c4973]" name="TearDown" is-config="true" duration-ms="2656" started-at="2018-11-01T10:35:09Z" finished-at="2018-11-01T10:35:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- TestCases.WeChatLogin -->
    </test> <!-- 微信登录流程 -->
  </suite> <!-- Appium测试报告 -->
</testng-results>
